<div id="reviewbooster_order_view_popup" class="message-popup show" style="position:fixed;">
  <div class="message-popup-head">
    <a href="#" onclick="closeMessagePopup(); return false;" title="close"><span>close</span></a>
    <h2><?php echo $this->__('Review Booster Testing Sending Reminder'); ?></h2>
  </div>
  <div class="message-popup-content">
    <form id="reviewbooster-test-send-form">
      <div class="fieldset">
        <ul class="form-list">
          <li>
            <label for="email_address" class="required"> <em>*</em> <?php echo $this->__('Email Address') ?></label>
            <div class="input-box">
              <input type="text" name="email" id='email_address' title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" style="width: 100%;"/>
            </div>
          </li>
        </ul>
        <div class="buttons-set" style="padding: 10px; text-align: center;">
          <button type='button' class="button" id="reminder_test_send_submit_button" title="<?php echo $this->__("Send"); ?>" onclick="review_test_submit()" style="width: 50%;">
            <span><span><?php echo $this->__("Send"); ?></span></span>
          </button>
        </div>
      </div>
    </form>
  </div>
</div>
<script type="text/javascript">
  $('reviewbooster_order_view_popup').hide();
  function reviewbooster_open_popup() {
    $('reviewbooster_order_view_popup').show();
    $('email_address').focus();
  }
  function closeMessagePopup() {
    $('reviewbooster_order_view_popup').hide();
  }

  var reviewbooster_test_form = new varienForm('reviewbooster-test-send-form');
  var submit_link = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/reviewboosteradmin/send_test_reminder',
  array(
    'order_id' => Mage::app()->getRequest()->getParam('order_id'),
  )); ?>';

  function review_test_submit() {
    if (reviewbooster_test_form.validator.validate()) {
      setLocation(submit_link + 'email_address' + "/" + $('email_address').value);
    }
  }

</script>